pimcore_install:
    info_message: Database credentials are set via <strong>platform.sh</strong>'s environment variables.
    copy_profile_files: false
    parameters:
        profile: demo-basic-twig
